apiVersion: v1
data:
  prometheus.yml: |-
    global:
      scrape_interval: 1s
      evaluation_interval: 15s

    remote_write:
      - url: "http://192.168.0.111:8080/receive"

    scrape_configs:
      - job_name: node
        static_configs:
        - targets: ['192.168.0.107:9100', '192.168.0.108:9100', '192.168.0.109:9100', '192.168.0.113:9100', '192.168.0.116:9100'] #se adicionar mais ip's, separar por virgula dentro dos colchetes
kind: ConfigMap
metadata:
  name: prometheus-2-server-conf
  labels:
    name: prometheus-2-server-conf
  namespace: monitoring2
