apiVersion: v1
kind: Service
metadata:
  name: prometheus-2-service
  namespace: monitoring2
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /metrics
      prometheus.io/port:   '9090'
  
spec:
  selector: 
    app: prometheus-2-server
  type: NodePort  
  ports:
    - port: 8080
      targetPort: 9090 
      nodePort: 30010
