---
kafka:
  host: "192.168.0.111"
  port: 9092
  topic: "sro-slice-1-log"
  reader: "kafka_influxdb.reader.confluent"
influxdb:
  host: "localhost"
  port: 8086
  user: "cloud"
  password: "necos"
  dbname: "slice_1_slas"
encoder: "kafka_influxdb.encoder.json_encoder"
buffer_size: 1
statistics: true
